version: '3'

services:
  redis:
    image: redis:3.2.10
    volumes:
      - ./.docker-data/redis:/data
    ports:
      - 6379:6379
  
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    volumes:
      - ./.docker-data/dynamo:/dynamodb_local_db
    ports:
      - 8000:8000
  
  battlesnake:
    image: sendwithus/battlesnake-server
    ports:
      - 3001:3000